# Generated by Django 6.0.7 on 2026-07-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderatör'), ('user', 'kullanıcı')], default='user', max_length=20),
        ),
    ]
